// Catégories disponibles pour le centre de formations
export const CATEGORIES = ['Compétences pro', 'IA et Tech', 'Excel et Data', 'Communication', 'Outils gratuits', 'Langues']

export const FORMATIONS = [
  {
    id: 'excel-avance',
    titre: 'Excel avancé',
    description: "Tableaux croisés dynamiques, formules complexes, macros VBA - de quoi arrêter de perdre trois heures sur un fichier qui devrait en prendre vingt minutes.",
    categorie: 'Excel et Data',
    niveau: 'Intermédiaire',
    duree: '10h',
    gratuit: true,
    lien: 'https://openclassrooms.com/fr/courses/7139456-perfectionnez-vous-sur-excel',
    metiers: ['comptable', 'assistant', 'commercial', 'finance'],
    competences: ['Tableaux croisés dynamiques', 'Formules avancées', 'Macros VBA', 'Mise en forme conditionnelle'],
  },
  {
    id: 'google-analytics',
    titre: 'Google Analytics',
    description: "Comprendre d'où viennent vos visiteurs et ce qu'ils font sur le site, avec la certification officielle de Google en prime.",
    categorie: 'Excel et Data',
    niveau: 'Débutant',
    duree: '4h',
    gratuit: true,
    lien: 'https://skillshop.exceedlms.com/student/path/525060-google-analytics-certification',
    metiers: ['marketing', 'communication'],
    competences: ['Suivi du trafic web', 'Rapports GA4', 'Conversions', 'Segmentation d\'audience'],
  },
  {
    id: 'prompt-engineering',
    titre: 'Prompt Engineering pour tous',
    description: "Le tutoriel interactif d'Anthropic pour apprendre à formuler des demandes claires à une IA et obtenir des réponses qui servent vraiment à quelque chose.",
    categorie: 'IA et Tech',
    niveau: 'Débutant',
    duree: '3h',
    gratuit: true,
    lien: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview',
    metiers: ['tous'],
    competences: ['Rédaction de prompts', 'Chain-of-thought', 'Structuration XML', 'Cas d\'usage concrets'],
  },
  {
    id: 'chatgpt-travail',
    titre: 'ChatGPT au travail',
    description: "Les bases pour intégrer ChatGPT dans son quotidien professionnel sans y perdre en fiabilité - via les cours gratuits d'OpenAI Academy.",
    categorie: 'IA et Tech',
    niveau: 'Débutant',
    duree: '2h',
    gratuit: true,
    lien: 'https://academy.openai.com',
    metiers: ['tous'],
    competences: ['Prompts efficaces', 'Vérification des réponses', 'Automatisation de tâches simples'],
  },
  {
    id: 'python-debutant',
    titre: 'Python débutant',
    description: "Le langage le plus demandé, expliqué sans jargon. De la première ligne de code à un vrai petit programme qui fonctionne.",
    categorie: 'IA et Tech',
    niveau: 'Débutant',
    duree: '15h',
    gratuit: true,
    lien: 'https://openclassrooms.com/fr/courses/7168871-apprenez-les-bases-du-langage-python',
    metiers: ['developpeur', 'data'],
    competences: ['Syntaxe Python', 'Variables et boucles', 'Fonctions', 'Manipulation de données'],
  },
  {
    id: 'gestion-de-projet',
    titre: 'Gestion de projet',
    description: "Le certificat professionnel Google pour piloter un projet de A à Z : planning, budget, équipe, imprévus.",
    categorie: 'Compétences pro',
    niveau: 'Débutant',
    duree: '~130h',
    gratuit: true,
    lien: 'https://www.coursera.org/professional-certificates/google-project-management',
    metiers: ['chef de projet', 'manager'],
    competences: ['Méthodes Agile et Scrum', 'Gestion des risques', 'Planification', 'Communication d\'équipe'],
  },
  {
    id: 'linkedin-optimisation',
    titre: 'LinkedIn optimisation',
    description: "Un profil LinkedIn qui donne envie de cliquer, pas un CV recopié tel quel. Titre, photo, résumé, recommandations.",
    categorie: 'Compétences pro',
    niveau: 'Débutant',
    duree: '1h',
    gratuit: true,
    lien: 'https://www.linkedin.com/learning/optimiser-son-profil-linkedin',
    metiers: ['tous'],
    competences: ['Optimisation du profil', 'Mots-clés de recherche', 'Réseau et visibilité'],
  },
  {
    id: 'prise-de-parole',
    titre: 'Prise de parole en public',
    description: "Gérer le trac, structurer un discours, capter une salle - les bases de l'art oratoire expliquées simplement en vidéo.",
    categorie: 'Communication',
    niveau: 'Débutant',
    duree: '2h',
    gratuit: true,
    lien: 'https://www.youtube.com/@NicolasMel',
    metiers: ['tous'],
    competences: ['Gestion du trac', 'Structure d\'un discours', 'Langage corporel', 'Impact vocal'],
  },
  {
    id: 'email-professionnel',
    titre: 'Email professionnel',
    description: "Rédiger des écrits professionnels clairs, bien structurés et qui vont droit au but - mails compris.",
    categorie: 'Communication',
    niveau: 'Débutant',
    duree: '4h',
    gratuit: true,
    lien: 'https://openclassrooms.com/fr/courses/4929676-redigez-des-ecrits-professionnels',
    metiers: ['tous'],
    competences: ['Structuration des idées', 'Ton professionnel', 'Formules de politesse', 'Relecture efficace'],
  },
  {
    id: 'canva-design',
    titre: 'Canva design',
    description: "Faire des visuels propres sans être designer : réseaux sociaux, présentations, supports de com. Par la Design School officielle de Canva.",
    categorie: 'Outils gratuits',
    niveau: 'Débutant',
    duree: '3h',
    gratuit: true,
    lien: 'https://www.canva.com/design-school/',
    metiers: ['marketing', 'communication', 'creatif'],
    competences: ['Composition visuelle', 'Templates et branding', 'Réseaux sociaux', 'Typographie de base'],
  },
  {
    id: 'notion-productivite',
    titre: 'Notion productivité',
    description: "Organiser son travail, ses notes et ses projets dans un seul outil, sans y passer plus de temps qu'avant.",
    categorie: 'Outils gratuits',
    niveau: 'Débutant',
    duree: '2h',
    gratuit: true,
    lien: 'https://www.youtube.com/c/NotionenFran%C3%A7ais',
    metiers: ['tous'],
    competences: ['Bases de données Notion', 'Templates', 'Organisation de projet'],
  },
  {
    id: 'api-rest',
    titre: 'API REST comprendre',
    description: "Ce que fait vraiment une API, comment l'interroger, et pourquoi tous les devs en parlent. Expliqué par Grafikart.",
    categorie: 'IA et Tech',
    niveau: 'Débutant',
    duree: '1h',
    gratuit: true,
    lien: 'https://www.youtube.com/watch?v=bqpXOT5mwW4',
    metiers: ['developpeur'],
    competences: ['Requêtes HTTP', 'Format JSON', 'Authentification API', 'Endpoints REST'],
  },
  {
    id: 'javascript-debutant',
    titre: 'JavaScript débutant',
    description: "Le langage qui fait tourner le web, appris pas à pas jusqu'à construire une vraie petite application.",
    categorie: 'IA et Tech',
    niveau: 'Débutant',
    duree: '12h',
    gratuit: true,
    lien: 'https://openclassrooms.com/fr/courses/7696886-apprenez-a-programmer-avec-javascript',
    metiers: ['developpeur'],
    competences: ['Syntaxe JavaScript', 'DOM et événements', 'Logique de programmation'],
  },
  {
    id: 'sql-debutant',
    titre: 'SQL débutant',
    description: "Écrire des requêtes pour extraire exactement l'information dont on a besoin dans une base de données.",
    categorie: 'Excel et Data',
    niveau: 'Débutant',
    duree: '8h',
    gratuit: true,
    lien: 'https://openclassrooms.com/fr/courses/7818671-requetez-une-base-de-donnees-avec-sql',
    metiers: ['developpeur', 'data'],
    competences: ['Requêtes SELECT', 'Jointures', 'Filtres et agrégations'],
  },
  {
    id: 'google-data-studio',
    titre: 'Google Data Studio',
    description: "Transformer des données brutes en rapports visuels clairs avec Looker Studio (ex Google Data Studio).",
    categorie: 'Excel et Data',
    niveau: 'Intermédiaire',
    duree: '3h',
    gratuit: true,
    lien: 'https://www.skills.google/paths/28/course_templates/1379',
    metiers: ['data', 'marketing'],
    competences: ['Connecteurs de données', 'Tableaux de bord', 'Visualisation de données'],
  },
  {
    id: 'communication-non-violente',
    titre: 'Communication non-violente',
    description: "Dire les choses sans blesser et désamorcer un conflit avant qu'il ne prenne des proportions inutiles.",
    categorie: 'Communication',
    niveau: 'Débutant',
    duree: '1h',
    gratuit: true,
    lien: 'https://www.youtube.com/watch?v=ATmuuslLFLc',
    metiers: ['manager', 'rh', 'tous'],
    competences: ['Écoute active', 'Expression des besoins', 'Gestion de conflit'],
  },
  {
    id: 'negociation-commerciale',
    titre: 'Négociation commerciale',
    description: "Les fondamentaux de la négociation par l'ESSEC : préparer, structurer, conclure sans laisser de valeur sur la table.",
    categorie: 'Communication',
    niveau: 'Intermédiaire',
    duree: '10h',
    gratuit: true,
    lien: 'https://www.coursera.org/learn/fondamentaux-negociation',
    metiers: ['commercial', 'manager'],
    competences: ['Préparation de négociation', 'Création de valeur', 'Gestion des blocages'],
  },
  {
    id: 'powerpoint-avance',
    titre: 'PowerPoint avancé',
    description: "Construire des présentations qui se lisent sans effort, avec les bons réflexes de mise en page et d'animation.",
    categorie: 'Outils gratuits',
    niveau: 'Intermédiaire',
    duree: '3h',
    gratuit: true,
    lien: 'https://learn.microsoft.com/en-us/training/educator-center/product-guides/powerpoint',
    metiers: ['tous'],
    competences: ['Mise en page de slides', 'Animations', 'Modèles réutilisables'],
  },
  {
    id: 'figma-debutant',
    titre: 'Figma débutant',
    description: "Les bases de Figma pour concevoir une interface ou une maquette sans partir de zéro à chaque fois.",
    categorie: 'Outils gratuits',
    niveau: 'Débutant',
    duree: '2h',
    gratuit: true,
    lien: 'https://www.youtube.com/watch?v=lgPtcrMp828',
    metiers: ['designer', 'creatif'],
    competences: ['Frames et composants', 'Prototypage', 'Bibliothèque de styles'],
  },
  {
    id: 'ia-pour-les-nuls',
    titre: 'IA pour les nuls',
    description: "Ce qu'est vraiment l'intelligence artificielle, sans le blabla marketing - par Microsoft Learn.",
    categorie: 'IA et Tech',
    niveau: 'Débutant',
    duree: '3h',
    gratuit: true,
    lien: 'https://learn.microsoft.com/fr-fr/training/modules/get-started-ai-fundamentals/',
    metiers: ['tous'],
    competences: ['Concepts clés de l\'IA', 'Machine learning', 'Usage responsable de l\'IA'],
  },
  {
    id: 'toeic-preparation',
    titre: 'TOEIC préparation',
    description: "S'entraîner aux formats réels du test TOEIC avec la chaîne officielle, pour ne pas découvrir l'épreuve le jour J.",
    categorie: 'Langues',
    niveau: 'Intermédiaire',
    duree: '5h',
    gratuit: true,
    lien: 'https://www.youtube.com/channel/UCXpl1usxA_ZAkdKuGipysYQ',
    metiers: ['international', 'tous'],
    competences: ['Listening TOEIC', 'Reading TOEIC', 'Gestion du temps d\'examen'],
  },
  {
    id: 'anglais-professionnel',
    titre: 'Anglais professionnel',
    description: "Une spécialisation Coursera pour gagner en aisance à l'écrit et à l'oral dans un contexte de travail.",
    categorie: 'Langues',
    niveau: 'Intermédiaire',
    duree: '40h',
    gratuit: true,
    lien: 'https://www.coursera.org/specializations/improve-english',
    metiers: ['tous'],
    competences: ['Expression orale', 'Rédaction professionnelle', 'Vocabulaire du monde du travail'],
  },
  {
    id: 'comptabilite-generale',
    titre: 'Comptabilité générale',
    description: "Les bases du plan comptable et des écritures courantes pour comprendre ce qui se passe vraiment dans un bilan.",
    categorie: 'Compétences pro',
    niveau: 'Débutant',
    duree: '6h',
    gratuit: true,
    lien: 'https://openclassrooms.com/fr/courses/4801106-initiez-vous-a-la-comptabilite',
    metiers: ['comptable', 'finance'],
    competences: ['Plan comptable général', 'Écritures courantes', 'Lecture d\'un bilan'],
  },
  {
    id: 'droit-travail-bases',
    titre: 'Droit du travail bases',
    description: "Contrats, temps de travail, relation employeur-salarié : le cadre légal expliqué sans jargon d'avocat.",
    categorie: 'Compétences pro',
    niveau: 'Débutant',
    duree: '5h',
    gratuit: true,
    lien: 'https://openclassrooms.com/fr/courses/4581041-gerez-la-relation-de-travail',
    metiers: ['rh', 'manager'],
    competences: ['Types de contrats', 'Temps de travail', 'Rupture du contrat'],
  },
  {
    id: 'data-analyse-python',
    titre: 'Data analyse avec Python',
    description: "Le certificat avancé de Google pour passer de l'analyse de données basique à des modèles statistiques avec Python.",
    categorie: 'Excel et Data',
    niveau: 'Avancé',
    duree: '~150h',
    gratuit: true,
    lien: 'https://www.coursera.org/professional-certificates/google-advanced-data-analytics',
    metiers: ['data', 'developpeur'],
    competences: ['Python pour la data', 'Statistiques', 'Régression', 'Machine learning de base'],
  },
]
