// Base de données des 200 plus grandes entreprises françaises
// avec leur ATS de recrutement et leur slug API
// Sources: Greenhouse API (gratuit), Lever API (gratuit), SmartRecruiters (public)
// Workday et SuccessFactors nécessitent du scraping HTML

export const ENTREPRISES = [
  // ═══ GREENHOUSE (API JSON publique gratuite) ═══════════════════════════
  { id: 1, nom: 'Decathlon', secteur: 'Commerce', ats: 'greenhouse', slug: 'decathlontechnology', careers_url: 'https://www.decathlon.fr/emploi' },
  { id: 2, nom: 'Doctolib', secteur: 'Tech/Santé', ats: 'greenhouse', slug: 'doctolib', careers_url: 'https://careers.doctolib.fr' },
  { id: 3, nom: 'Criteo', secteur: 'Tech', ats: 'custom', slug: null, careers_url: 'https://careers.criteo.com' },
  { id: 4, nom: 'Contentsquare', secteur: 'Tech', ats: 'lever', slug: 'contentsquare', careers_url: 'https://contentsquare.com/careers' },
  { id: 5, nom: 'Qonto', secteur: 'Fintech', ats: 'greenhouse', slug: 'qonto', careers_url: 'https://qonto.com/fr/jobs' },
  { id: 6, nom: 'Alan', secteur: 'Insurtech', ats: 'ashby', slug: 'alan', careers_url: 'https://alan.com/fr/jobs' },
  { id: 7, nom: 'Swile', secteur: 'RH Tech', ats: 'greenhouse', slug: 'swile', careers_url: 'https://www.swile.co/fr/emplois' },
  { id: 8, nom: 'ManoMano', secteur: 'E-commerce', ats: 'lever', slug: 'manomano', careers_url: 'https://www.manomano.fr/jobs' },
  { id: 9, nom: 'BlaBlaCar', secteur: 'Mobilité', ats: 'lever', slug: 'blablacar', careers_url: 'https://blog.blablacar.fr/blablalife/blablacar-jobs' },
  { id: 10, nom: 'Withings', secteur: 'HealthTech', ats: 'workable', slug: 'withings', careers_url: 'https://www.withings.com/fr/fr/jobs' },
  { id: 11, nom: 'Deezer', secteur: 'Music Tech', ats: 'greenhouse', slug: 'deezer', careers_url: 'https://www.deezer.com/fr/company/jobs' },
  { id: 12, nom: 'Mirakl', secteur: 'SaaS', ats: 'greenhouse', slug: 'mirakl', careers_url: 'https://www.mirakl.com/fr/careers' },
  { id: 13, nom: 'Talend', secteur: 'Tech/Data', ats: 'greenhouse', slug: 'talend', careers_url: 'https://www.talend.com/company/jobs' },
  { id: 14, nom: 'Vestiaire Collective', secteur: 'Mode/E-commerce', ats: 'lever', slug: 'vestiairecollective', careers_url: 'https://jobs.vestiairecollective.com' },
  { id: 15, nom: 'Kyriba', secteur: 'Fintech', ats: 'greenhouse', slug: 'kyriba', careers_url: 'https://www.kyriba.com/about/careers' },
  { id: 16, nom: 'Meero', secteur: 'Tech/Photo', ats: 'greenhouse', slug: 'meero', careers_url: 'https://www.meero.com/fr/jobs' },
  { id: 17, nom: 'Back Market', secteur: 'E-commerce', ats: 'ashby', slug: 'backmarket', careers_url: 'https://jobs.backmarket.com' },
  { id: 18, nom: 'Ledger', secteur: 'Crypto/Tech', ats: 'lever', slug: 'ledger', careers_url: 'https://www.ledger.com/join-us' },
  { id: 19, nom: 'Spendesk', secteur: 'Fintech', ats: 'lever', slug: 'spendesk', careers_url: 'https://www.spendesk.com/fr/careers' },
  { id: 20, nom: 'Ankorstore', secteur: 'B2B Commerce', ats: 'ashby', slug: 'ankorstore', careers_url: 'https://www.ankorstore.com/jobs' },
  { id: 21, nom: 'Accor', secteur: 'Hôtellerie', ats: 'smartrecruiters', slug: 'accor', careers_url: 'https://careers.accor.com' },
  { id: 22, nom: 'Publicis Groupe', secteur: 'Communication', ats: 'greenhouse', slug: 'publicisgroupe', careers_url: 'https://www.publicisgroupe.com/fr/carrieres' },
  { id: 23, nom: 'Thales DMS', secteur: 'Défense/Tech', ats: 'smartrecruiters', slug: 'thales', careers_url: 'https://www.thalesgroup.com/fr/candidats' },
  { id: 24, nom: 'Payfit', secteur: 'RH Tech', ats: 'lever', slug: 'payfit', careers_url: 'https://payfit.com/fr/carriere' },
  { id: 25, nom: 'Pennylane', secteur: 'Fintech', ats: 'ashby', slug: 'pennylane', careers_url: 'https://www.pennylane.com/fr/jobs' },
  { id: 26, nom: 'Pigment', secteur: 'SaaS', ats: 'lever', slug: 'pigment', careers_url: 'https://www.pigment.com/fr/careers' },
  { id: 27, nom: 'Luko', secteur: 'Insurtech', ats: 'lever', slug: 'luko', careers_url: 'https://www.luko.eu/fr/careers' },
  { id: 28, nom: 'Alma', secteur: 'Fintech', ats: 'greenhouse', slug: 'alma', careers_url: 'https://www.getalma.eu/fr/jobs' },
  { id: 29, nom: 'Ateme', secteur: 'Tech', ats: 'greenhouse', slug: 'ateme', careers_url: 'https://www.ateme.com/company/careers' },
  { id: 30, nom: 'Maif', secteur: 'Assurance', ats: 'greenhouse', slug: 'maif', careers_url: 'https://www.maif.fr/qui-sommes-nous/travailler-chez-maif.html' },

  // ═══ LEVER (API JSON publique gratuite) ════════════════════════════════
  { id: 31, nom: 'Meetic', secteur: 'Tech/Dating', ats: 'lever', slug: 'meetic', careers_url: 'https://jobs.lever.co/meetic' },
  { id: 32, nom: 'Sunrise', secteur: 'Tech', ats: 'greenhouse', slug: 'sunrise', careers_url: 'https://jobs.lever.co/sunrise' },
  { id: 33, nom: 'Skello', secteur: 'RH Tech', ats: 'lever', slug: 'skello', careers_url: 'https://jobs.lever.co/skello' },
  { id: 34, nom: 'Shine', secteur: 'Fintech', ats: 'rippling', slug: 'shine', careers_url: 'https://jobs.lever.co/shine-1' },
  { id: 35, nom: 'Akeneo', secteur: 'SaaS', ats: 'lever', slug: 'akeneo', careers_url: 'https://jobs.lever.co/akeneo' },
  { id: 36, nom: 'Algolia', secteur: 'Tech/Search', ats: 'greenhouse', slug: 'algolia', careers_url: 'https://www.algolia.com/careers' },
  { id: 37, nom: 'Talentsoft', secteur: 'RH Tech', ats: 'lever', slug: 'talentsoft', careers_url: 'https://jobs.lever.co/talentsoft' },
  { id: 38, nom: 'Nuxeo', secteur: 'Tech', ats: 'lever', slug: 'nuxeo', careers_url: 'https://jobs.lever.co/nuxeo' },
  { id: 39, nom: 'Dataiku', secteur: 'AI/Data', ats: 'greenhouse', slug: 'dataiku', careers_url: 'https://www.dataiku.com/company/jobs' },
  { id: 40, nom: 'Devialet', secteur: 'Audio Tech', ats: 'lever', slug: 'devialet', careers_url: 'https://jobs.lever.co/devialet' },
  { id: 41, nom: 'Doctrine', secteur: 'LegalTech', ats: 'lever', slug: 'doctrine', careers_url: 'https://jobs.lever.co/doctrine' },
  { id: 42, nom: 'Exotec', secteur: 'Robotique', ats: 'workable', slug: 'exotec', careers_url: 'https://jobs.lever.co/exotec' },
  { id: 43, nom: 'Inato', secteur: 'HealthTech', ats: 'ashby', slug: 'inato', careers_url: 'https://jobs.lever.co/inato' },
  { id: 44, nom: 'Lifen', secteur: 'HealthTech', ats: 'lever', slug: 'lifen', careers_url: 'https://jobs.lever.co/lifen' },
  { id: 45, nom: 'Lydia Solutions', secteur: 'Fintech', ats: 'lever', slug: 'lydia', careers_url: 'https://jobs.lever.co/lydia' },

  // ═══ SMARTRECRUITERS (API publique) ════════════════════════════════════
  { id: 46, nom: 'LVMH', secteur: 'Luxe', ats: 'smartrecruiters', slug: 'LVMH', careers_url: 'https://careers.smartrecruiters.com/LVMH' },
  { id: 47, nom: "L'Oréal", secteur: 'Beauté/Luxe', ats: 'smartrecruiters', slug: 'lorealgroup', workday_id: 'loreal', careers_url: 'https://careers.loreal.com' },
  { id: 48, nom: 'Kering', secteur: 'Luxe', ats: 'smartrecruiters', slug: 'Kering', careers_url: 'https://careers.kering.com' },
  { id: 49, nom: 'Fnac Darty', secteur: 'Commerce', ats: 'smartrecruiters', slug: 'FnacDarty', careers_url: 'https://careers.smartrecruiters.com/FnacDarty' },
  { id: 50, nom: 'Auchan', secteur: 'Distribution', ats: 'smartrecruiters', slug: 'Auchan', careers_url: 'https://careers.smartrecruiters.com/Auchan' },
  { id: 51, nom: 'Leroy Merlin', secteur: 'Bricolage', ats: 'smartrecruiters', slug: 'LeroyMerlin', careers_url: 'https://careers.smartrecruiters.com/LeroyMerlin' },
  { id: 52, nom: 'Maisons du Monde', secteur: 'Déco', ats: 'workday', workday_id: 'maisonsdumonde', workday_path: 'Site_carriere', workday_subdomain: 'wd3', careers_url: 'https://maisonsdumonde.wd3.myworkdayjobs.com' },
  { id: 53, nom: 'Club Med', secteur: 'Tourisme', ats: 'smartrecruiters', slug: 'ClubMed', careers_url: 'https://careers.smartrecruiters.com/ClubMed' },
  { id: 54, nom: 'Pierre & Vacances', secteur: 'Tourisme', ats: 'smartrecruiters', slug: 'PierreEtVacances', careers_url: 'https://careers.smartrecruiters.com/PierreEtVacances' },
  { id: 55, nom: 'Groupe SEB', secteur: 'Industrie', ats: 'smartrecruiters', slug: 'GroupeSEB', careers_url: 'https://careers.smartrecruiters.com/GroupeSEB' },
  { id: 56, nom: 'Hermès', secteur: 'Luxe', ats: 'personio', slug: 'Hermes', careers_url: 'https://carrieres.hermes.com' },
  { id: 57, nom: 'Kiabi', secteur: 'Mode', ats: 'smartrecruiters', slug: 'Kiabi', careers_url: 'https://careers.smartrecruiters.com/Kiabi' },
  { id: 58, nom: 'Veepee', secteur: 'E-commerce', ats: 'lever', slug: 'veepee', careers_url: 'https://careers.smartrecruiters.com/Veepee' },
  { id: 59, nom: 'Boulanger', secteur: 'Commerce', ats: 'smartrecruiters', slug: 'Boulanger', careers_url: 'https://careers.smartrecruiters.com/Boulanger' },
  { id: 60, nom: 'Cdiscount', secteur: 'E-commerce', ats: 'smartrecruiters', slug: 'Cdiscount', careers_url: 'https://careers.smartrecruiters.com/Cdiscount' },

  // ═══ WORKDAY (scraping HTML — URL standardisée) ═════════════════════
  { id: 61, nom: 'Sanofi', secteur: 'Pharma', ats: 'workday', slug: 'sanofi', workday_id: 'sanofi', workday_path: 'sanofiCareers', workday_subdomain: 'wd3', careers_url: 'https://www.sanofi.com/fr/nous-rejoindre' },
  { id: 62, nom: 'AXA', secteur: 'Assurance', ats: 'workday', slug: 'axa', workday_id: 'axa', workday_path: 'AXA_Careers', careers_url: 'https://careers.axa.com' },
  { id: 63, nom: 'Danone', secteur: 'Agroalimentaire', ats: 'custom', slug: null, careers_url: 'https://talent.careers.danone.com/jobs' },
  { id: 64, nom: 'Schneider Electric', secteur: 'Industrie', ats: 'personio', slug: 'schneider', careers_url: 'https://www.se.com/fr/fr/about-us/careers' },
  { id: 65, nom: 'Saint-Gobain', secteur: 'Industrie/Construction', ats: 'smartrecruiters', slug: 'saintgobain', careers_url: 'https://careers.saint-gobain.com' },
  { id: 66, nom: 'Engie', secteur: 'Énergie', ats: 'workday', slug: 'engie', workday_id: 'engie', workday_path: 'ENGIE', careers_url: 'https://www.engie.com/groupe/carrieres' },
  { id: 67, nom: 'Air Liquide', secteur: 'Industrie/Gaz', ats: 'greenhouse', slug: 'air', careers_url: 'https://www.airliquide.com/groupe/carriere' },
  { id: 68, nom: 'Pernod Ricard', secteur: 'Spiritueux', ats: 'workday', slug: 'pernodricard', workday_id: 'pernodricard', workday_path: 'pernod-ricard', careers_url: 'https://careers.pernod-ricard.com' },
  { id: 69, nom: 'Legrand', secteur: 'Électrotechnique', ats: 'custom', slug: null, careers_url: 'https://www.legrandgroup.com/en/working-at-legrand' },
  { id: 70, nom: 'Dassault Systèmes', secteur: 'Tech/Logiciel', ats: 'workday', slug: 'dassaultsystemes', workday_id: 'ds', careers_url: 'https://www.3ds.com/fr/carrieres' },
  { id: 71, nom: 'Sodexo', secteur: 'Services', ats: 'smartrecruiters', slug: 'sodexo', careers_url: 'https://fr.sodexo.com/carrieres' },
  { id: 72, nom: 'Veolia', secteur: 'Environnement', ats: 'workday', slug: 'veolia', workday_id: 'veolia', careers_url: 'https://www.veolia.com/fr/carrieres' },
  { id: 73, nom: 'Rexel', secteur: 'Distribution électrique', ats: 'workday', slug: 'rexel', workday_id: 'rexel', careers_url: 'https://www.rexel.fr/carrieres' },
  { id: 74, nom: 'BioMérieux', secteur: 'Pharma/Diagnostics', ats: 'workday', slug: 'biomerieux', workday_id: 'biomerieux', careers_url: 'https://jobs.biomerieux.com' },
  { id: 75, nom: 'EssilorLuxottica', secteur: 'Optique', ats: 'smartrecruiters', slug: 'essilorluxottica', careers_url: 'https://careers.essilorluxottica.com' },
  { id: 76, nom: 'Stellantis', secteur: 'Automobile', ats: 'workday', slug: 'stellantis', workday_id: 'stellantis', careers_url: 'https://www.stellantis.com/fr/carrieres' },
  { id: 77, nom: 'Amundi', secteur: 'Finance/Gestion', ats: 'workday', slug: 'amundi', workday_id: 'amundi', careers_url: 'https://www.amundi.com/fr/carrieres' },
  { id: 78, nom: 'Nexans', secteur: 'Industrie/Câbles', ats: 'workday', slug: 'nexans', workday_id: 'nexans', careers_url: 'https://www.nexans.com/fr/carrieres' },
  { id: 79, nom: 'Imerys', secteur: 'Industrie/Minéraux', ats: 'workday', slug: 'imerys', workday_id: 'imerys', careers_url: 'https://www.imerys.com/fr/carrieres' },
  { id: 80, nom: 'Bureau Veritas', secteur: 'Services', ats: 'ashby', slug: 'bureau', careers_url: 'https://jobs.bureauveritas.com' },
  { id: 81, nom: 'Michelin', secteur: 'Industrie/Pneumatiques', ats: 'workday', slug: 'michelin', workday_id: 'michelinhr', workday_path: 'Michelin', careers_url: 'https://www.michelin.com/fr/carrieres' },
  { id: 82, nom: 'Plastic Omnium', secteur: 'Automobile', ats: 'rippling', slug: 'plastic', careers_url: 'https://www.plastic-omnium.com/fr/carrieres' },
  { id: 83, nom: 'Rémy Cointreau', secteur: 'Spiritueux', ats: 'workday', slug: 'remycointreau', workday_id: 'remycointreau', careers_url: 'https://careers.remy-cointreau.com' },
  { id: 84, nom: 'Safran', secteur: 'Aéronautique', ats: 'workday', slug: 'safran', workday_id: 'safran', workday_path: 'Safran', careers_url: 'https://www.safran-group.com/fr/carrieres' },
  { id: 85, nom: 'Thales', secteur: 'Défense/Aéro', ats: 'smartrecruiters', slug: 'thales', careers_url: 'https://www.thalesgroup.com/fr/candidats' },
  { id: 86, nom: 'Korian', secteur: 'Santé/Ehpad', ats: 'workday', slug: 'korian', workday_id: 'korian', careers_url: 'https://www.korian.fr/recrutement' },
  { id: 87, nom: 'Ipsen', secteur: 'Pharma', ats: 'workday', slug: 'ipsen', workday_id: 'ipsen', workday_path: 'ipsen_Careers', workday_subdomain: 'wd3', careers_url: 'https://www.ipsen.com/fr/carrieres' },
  { id: 88, nom: 'Vallourec', secteur: 'Industrie/Tubes', ats: 'workday', slug: 'vallourec', workday_id: 'vallourec', careers_url: 'https://www.vallourec.com/fr/carrieres' },
  { id: 89, nom: 'Servier', secteur: 'Pharma', ats: 'workday', slug: 'servier', workday_id: 'servier', careers_url: 'https://www.servier.fr/nous-rejoindre' },
  { id: 90, nom: 'Eurofins', secteur: 'Sciences/Tests', ats: 'smartrecruiters', slug: 'eurofins', careers_url: 'https://careers.eurofins.com' },

  // ═══ SAP SUCCESSFACTORS ═════════════════════════════════════════════
  { id: 91, nom: 'TotalEnergies', secteur: 'Énergie', ats: 'successfactors', slug: 'totalenergies', careers_url: 'https://totalenergies.com/fr/carrieres' },
  { id: 92, nom: 'Airbus', secteur: 'Aéronautique', ats: 'successfactors', slug: 'airbus', careers_url: 'https://www.airbus.com/fr/carrieres' },
  { id: 93, nom: 'Renault', secteur: 'Automobile', ats: 'successfactors', slug: 'renault', careers_url: 'https://www.renault.com/fr/carrieres.html' },
  { id: 94, nom: 'Orange', secteur: 'Télécoms', ats: 'successfactors', slug: 'orange', careers_url: 'https://orange.jobs' },
  { id: 95, nom: 'Arkema', secteur: 'Chimie', ats: 'successfactors', slug: 'arkema', careers_url: 'https://www.arkema.com/fr/carrieres' },
  { id: 96, nom: 'Alstom', secteur: 'Transport ferroviaire', ats: 'successfactors', slug: 'alstom', careers_url: 'https://www.alstom.com/fr/carrieres' },
  { id: 97, nom: 'Deloitte France', secteur: 'Conseil/Audit', ats: 'workday', slug: 'deloitte', careers_url: 'https://www.deloitte.com/fr/fr/careers.html' },
  { id: 98, nom: 'Société Générale', secteur: 'Banque', ats: 'successfactors', slug: 'societegenerale', careers_url: 'https://careers.societegenerale.com' },
  { id: 99, nom: 'Bouygues Telecom', secteur: 'Télécoms', ats: 'successfactors', slug: 'bouyguestelecom', careers_url: 'https://www.bouyguestelecom.fr/carrieres' },
  { id: 100, nom: 'EDF', secteur: 'Énergie', ats: 'successfactors', slug: 'edf', careers_url: 'https://www.edf.fr/groupe-edf/carrieres' },

  // ═══ CUSTOM / TALEO / PAGES CARRIÈRES DIRECTES ══════════════════════
  { id: 101, nom: 'BNP Paribas', secteur: 'Banque', ats: 'custom', slug: null, careers_url: 'https://group.bnpparibas/carrieres' },
  { id: 102, nom: 'Carrefour', secteur: 'Distribution', ats: 'custom', slug: null, careers_url: 'https://www.carrefour.com/fr/groupe/emploi' },
  { id: 103, nom: 'Vinci', secteur: 'Construction', ats: 'taleo', slug: 'vinci', careers_url: 'https://www.vinci.com/vinci.nsf/fr/emploi.htm' },
  { id: 104, nom: 'Bouygues Construction', secteur: 'Construction', ats: 'custom', slug: null, careers_url: 'https://www.bouygues-construction.com/fr/nous-rejoindre' },
  { id: 105, nom: 'Vivendi', secteur: 'Médias', ats: 'custom', slug: null, careers_url: 'https://www.vivendi.com/carrieres' },
  { id: 106, nom: 'SNCF', secteur: 'Transport', ats: 'custom', slug: null, careers_url: 'https://www.sncf.com/fr/recrutement' },
  { id: 107, nom: 'RATP', secteur: 'Transport', ats: 'custom', slug: null, careers_url: 'https://www.ratp.fr/nous-rejoindre' },
  { id: 108, nom: 'La Poste', secteur: 'Services postaux', ats: 'custom', slug: null, careers_url: 'https://www.laposte.fr/nous-rejoindre' },
  { id: 109, nom: 'EDF Renouvelables', secteur: 'Énergie', ats: 'custom', slug: null, careers_url: 'https://www.edf-renouvelables.com/carrieres' },
  { id: 110, nom: 'Crédit Agricole', secteur: 'Banque', ats: 'taleo', slug: 'creditagricole', careers_url: 'https://www.credit-agricole.com/carrieres' },
  { id: 111, nom: 'Natixis', secteur: 'Finance', ats: 'custom', slug: null, careers_url: 'https://www.natixis.com/natixis/jcms/j_5/fr/recrutement' },
  { id: 112, nom: 'Lagardère', secteur: 'Médias', ats: 'custom', slug: null, careers_url: 'https://www.lagardere.com/carrieres' },
  { id: 113, nom: 'Accor Hotels', secteur: 'Hôtellerie', ats: 'smartrecruiters', slug: 'accor', careers_url: 'https://careers.accor.com' },
  { id: 114, nom: 'Elior Group', secteur: 'Restauration collective', ats: 'custom', slug: null, careers_url: 'https://www.eliorgroup.com/carrieres' },
  { id: 115, nom: 'Eiffage', secteur: 'Construction', ats: 'workday', slug: 'eiffage', workday_id: 'eiffage', workday_path: 'eiffage_Careers', workday_subdomain: 'wd3', careers_url: 'https://www.eiffage.com/carrieres' },
  { id: 116, nom: 'Colas', secteur: 'Construction', ats: 'custom', slug: null, careers_url: 'https://www.colas.com/fr/carrieres' },
  { id: 117, nom: 'Alten', secteur: 'Ingénierie/Conseil', ats: 'smartrecruiters', slug: 'alten', careers_url: 'https://www.alten.fr/carrieres' },
  { id: 118, nom: 'Teleperformance', secteur: 'Services', ats: 'recruitee', slug: 'teleperformance', careers_url: 'https://jobs.teleperformance.com' },
  { id: 119, nom: 'Sopra Steria', secteur: 'Conseil IT', ats: 'custom', slug: null, careers_url: 'https://www.soprasteria.com/fr/carrieres' },
  { id: 120, nom: 'Atos', secteur: 'Tech/IT', ats: 'custom', slug: null, careers_url: 'https://atos.net/fr/carrieres' },

  // ═══ GRANDS GROUPES ADDITIONNELS ════════════════════════════════════
  { id: 121, nom: 'Capgemini', secteur: 'Conseil IT', ats: 'greenhouse', slug: 'capgemini', careers_url: 'https://www.capgemini.com/fr-fr/carrieres' },
  { id: 122, nom: 'Dior', secteur: 'Luxe', ats: 'smartrecruiters', slug: 'Dior', careers_url: 'https://careers.dior.com' },
  { id: 123, nom: 'Chanel', secteur: 'Luxe', ats: 'smartrecruiters', slug: 'Chanel', careers_url: 'https://www.chanel.com/fr/carrieres' },
  { id: 124, nom: 'Richemont/Cartier', secteur: 'Luxe', ats: 'workday', slug: 'richemont', careers_url: 'https://careers.richemont.com' },
  { id: 125, nom: 'Pierre Fabre', secteur: 'Pharma/Cosmétique', ats: 'workday', workday_id: 'pierrefabre', workday_path: 'External_Career_Site', workday_subdomain: 'wd3', careers_url: 'https://www.pierre-fabre.com/fr/nous-rejoindre' },
  { id: 126, nom: 'Biomérieux', secteur: 'Diagnostics', ats: 'workday', slug: 'biomerieux2', careers_url: 'https://jobs.biomerieux.com' },
  { id: 127, nom: 'Sartorius Stedim', secteur: 'Biotech', ats: 'workday', slug: 'sartorius', workday_id: 'sartorius', workday_path: 'sartoriusCareers', workday_subdomain: 'wd3', careers_url: 'https://jobs.sartorius.com' },
  { id: 128, nom: 'Eurazeo', secteur: 'Finance/PE', ats: 'custom', slug: null, careers_url: 'https://www.eurazeo.com/fr/carrieres' },
  { id: 129, nom: 'Coface', secteur: 'Assurance crédit', ats: 'smartrecruiters', slug: 'coface', careers_url: 'https://www.coface.com/fr/Carrieres' },
  { id: 130, nom: 'BIC', secteur: 'Industrie/Papeterie', ats: 'smartrecruiters', slug: 'bictech', careers_url: 'https://www.bic.com/fr/fr/nous-rejoindre.html' },
  { id: 131, nom: 'Soitec', secteur: 'Semi-conducteurs', ats: 'workday', slug: 'soitec', careers_url: 'https://www.soitec.com/fr/carrieres' },
  { id: 132, nom: 'CGG', secteur: 'Géosciences', ats: 'custom', slug: null, careers_url: 'https://www.cgg.com/fr/carrieres' },
  { id: 133, nom: 'Derichebourg', secteur: 'Services/Recyclage', ats: 'personio', slug: 'derichebourg', careers_url: 'https://www.derichebourg.com/recrutement' },
  { id: 134, nom: 'Getlink', secteur: 'Transport', ats: 'recruitee', slug: 'getlink', careers_url: 'https://www.getlinkgroup.com/fr/carrieres' },
  { id: 135, nom: 'BPCE', secteur: 'Banque', ats: 'custom', slug: null, careers_url: 'https://www.bpce.fr/groupe-bpce/nous-rejoindre' },
  { id: 136, nom: 'Banque Postale', secteur: 'Banque', ats: 'custom', slug: null, careers_url: 'https://www.labanquepostale.fr/recrutement' },
  { id: 137, nom: 'CNP Assurances', secteur: 'Assurance', ats: 'custom', slug: null, careers_url: 'https://www.cnp.fr/nous-rejoindre' },
  { id: 138, nom: 'MAAF', secteur: 'Assurance', ats: 'custom', slug: null, careers_url: 'https://www.maaf.fr/carriere' },
  { id: 139, nom: 'Groupama', secteur: 'Assurance', ats: 'custom', slug: null, careers_url: 'https://www.groupama.com/fr/recrutement' },
  { id: 140, nom: 'GMF', secteur: 'Assurance', ats: 'custom', slug: null, careers_url: 'https://www.gmf.fr/nous-rejoindre' },

  // ═══ RETAIL ET GRANDE DISTRIBUTION ══════════════════════════════════
  { id: 141, nom: 'Intermarché', secteur: 'Grande distribution', ats: 'smartrecruiters', slug: 'intermarche', careers_url: 'https://www.intermarche.com/carrieres' },
  { id: 142, nom: 'Casino', secteur: 'Grande distribution', ats: 'custom', slug: null, careers_url: 'https://www.groupe-casino.fr/carrieres' },
  { id: 143, nom: 'Système U', secteur: 'Grande distribution', ats: 'custom', slug: null, careers_url: 'https://www.magasins-u.com/recrutement' },
  { id: 144, nom: 'Picard', secteur: 'Alimentaire', ats: 'recruitee', slug: 'Picard', careers_url: 'https://carrieres.picard.fr' },
  { id: 145, nom: 'Bricorama', secteur: 'Bricolage', ats: 'custom', slug: null, careers_url: 'https://www.bricorama.fr/recrutement' },
  { id: 146, nom: 'Monoprix', secteur: 'Distribution', ats: 'custom', slug: null, careers_url: 'https://www.monoprix.fr/cms/c/recrutement' },
  { id: 147, nom: 'H&M France', secteur: 'Mode', ats: 'successfactors', slug: 'hm', careers_url: 'https://career.hm.com' },
  { id: 148, nom: 'Zara France', secteur: 'Mode', ats: 'custom', slug: null, careers_url: 'https://www.inditex.com/fr/carrieres' },
  { id: 149, nom: 'Sephora', secteur: 'Beauté/Retail', ats: 'smartrecruiters', slug: 'Sephora', careers_url: 'https://careers.smartrecruiters.com/Sephora' },
  { id: 150, nom: 'Yves Rocher', secteur: 'Beauté', ats: 'custom', slug: null, careers_url: 'https://www.yves-rocher.fr/carrieres' },

  // ═══ TECH ET STARTUPS FRANÇAISES ═════════════════════════════════════
  { id: 151, nom: 'OVHcloud', secteur: 'Cloud/Tech', ats: 'greenhouse', slug: 'ovhcloud', careers_url: 'https://www.ovhcloud.com/fr/company/jobs' },
  { id: 152, nom: 'Infomaniak', secteur: 'Cloud/Tech', ats: 'custom', slug: null, careers_url: 'https://www.infomaniak.com/fr/jobs' },
  { id: 153, nom: 'Dailymotion', secteur: 'Vidéo/Tech', ats: 'smartrecruiters', slug: 'dailymotion', careers_url: 'https://www.dailymotion.com/fr/careers' },
  { id: 154, nom: 'Voodoo', secteur: 'Jeux vidéo', ats: 'ashby', slug: 'voodoo', careers_url: 'https://www.voodoo.io/jobs' },
  { id: 155, nom: 'Homa Games', secteur: 'Jeux vidéo', ats: 'lever', slug: 'homagames', careers_url: 'https://jobs.lever.co/homagames' },
  { id: 156, nom: 'Ubisoft', secteur: 'Jeux vidéo', ats: 'greenhouse', slug: 'ubisoft', careers_url: 'https://www.ubisoft.com/fr-fr/company/careers' },
  { id: 157, nom: 'Gameloft', secteur: 'Jeux vidéo', ats: 'smartrecruiters', slug: 'gameloft', careers_url: 'https://www.gameloft.com/careers' },
  { id: 158, nom: 'Dalkia', secteur: 'Énergie services', ats: 'custom', slug: null, careers_url: 'https://www.dalkia.fr/nous-rejoindre' },
  { id: 159, nom: 'Nexity', secteur: 'Immobilier', ats: 'smartrecruiters', slug: 'nexity', careers_url: 'https://www.nexity.fr/carrieres' },
  { id: 160, nom: 'Icade', secteur: 'Immobilier', ats: 'custom', slug: null, careers_url: 'https://www.icade.fr/carrieres' },

  // ═══ SANTÉ ET PHARMA ════════════════════════════════════════════════
  { id: 161, nom: 'Ramsay Santé', secteur: 'Santé', ats: 'custom', slug: null, careers_url: 'https://www.ramsaysante.fr/recrutement' },
  { id: 162, nom: 'Orpea', secteur: 'Santé/EHPAD', ats: 'workday', slug: 'orpea', careers_url: 'https://www.orpea.fr/carrieres' },
  { id: 163, nom: 'Almirall', secteur: 'Pharma', ats: 'workday', slug: 'almirall', careers_url: 'https://www.almirall.fr/carrieres' },
  { id: 164, nom: 'Boehringer Ingelheim', secteur: 'Pharma', ats: 'workday', slug: 'boehringer', careers_url: 'https://www.boehringer-ingelheim.com/fr/carrieres' },
  { id: 165, nom: 'Guerbet', secteur: 'Pharma/Imagerie', ats: 'workday', slug: 'guerbet', careers_url: 'https://www.guerbet.com/fr/rejoignez-nous' },
  { id: 166, nom: 'Laboratoire Expanscience', secteur: 'Pharma', ats: 'custom', slug: null, careers_url: 'https://www.expanscience.com/carrieres' },
  { id: 167, nom: 'Biomnis', secteur: 'Biologie médicale', ats: 'custom', slug: null, careers_url: 'https://www.biomnis.com/recrutement' },
  { id: 168, nom: 'Hartmann France', secteur: 'Médical', ats: 'custom', slug: null, careers_url: 'https://www.hartmann.info/fr-fr/carrieres' },
  { id: 169, nom: 'Zambon France', secteur: 'Pharma', ats: 'custom', slug: null, careers_url: 'https://www.zambon.com/fr/carrieres' },
  { id: 170, nom: 'DBV Technologies', secteur: 'Biotech', ats: 'greenhouse', slug: 'dbvtechnologies', careers_url: 'https://www.dbv-technologies.com/jobs' },

  // ═══ CONSEIL ET SERVICES PROFESSIONNELS ══════════════════════════════
  { id: 171, nom: 'McKinsey France', secteur: 'Conseil stratégique', ats: 'workday', slug: 'mckinsey', careers_url: 'https://www.mckinsey.com/fr/carrieres' },
  { id: 172, nom: 'BCG France', secteur: 'Conseil stratégique', ats: 'greenhouse', slug: 'bcg', careers_url: 'https://www.bcg.com/fr-fr/careers' },
  { id: 173, nom: 'Bain & Company France', secteur: 'Conseil stratégique', ats: 'workday', slug: 'bain', careers_url: 'https://www.bain.com/fr/carrieres' },
  { id: 174, nom: 'Accenture France', secteur: 'Conseil IT', ats: 'workday', slug: 'accenture', careers_url: 'https://www.accenture.com/fr-fr/careers' },
  { id: 175, nom: 'EY France', secteur: 'Audit/Conseil', ats: 'custom', slug: null, careers_url: 'https://www.ey.com/fr_fr/careers' },
  { id: 176, nom: 'PwC France', secteur: 'Audit/Conseil', ats: 'workday', slug: 'pwcfrance', careers_url: 'https://careers.pwc.fr' },
  { id: 177, nom: 'KPMG France', secteur: 'Audit/Conseil', ats: 'custom', slug: null, careers_url: 'https://home.kpmg/fr/fr/home/carrieres.html' },
  { id: 178, nom: 'Grant Thornton', secteur: 'Audit/Conseil', ats: 'recruitee', slug: 'grantthornton', careers_url: 'https://www.grant-thornton.fr/carrieres' },
  { id: 179, nom: 'Wavestone', secteur: 'Conseil stratégique/IT', ats: 'greenhouse', slug: 'wavestone', careers_url: 'https://www.wavestone.com/carrieres' },
  { id: 180, nom: 'Sia Partners', secteur: 'Conseil', ats: 'smartrecruiters', slug: 'sia', careers_url: 'https://www.sia-partners.com/fr/carrieres' },

  // ═══ INDUSTRIE ET INGÉNIERIE ══════════════════════════════════════════
  { id: 181, nom: 'Framatome', secteur: 'Nucléaire', ats: 'successfactors', slug: 'framatome', careers_url: 'https://www.framatome.com/fr/carrieres' },
  { id: 182, nom: 'Naval Group', secteur: 'Défense navale', ats: 'successfactors', slug: 'navalgroup', careers_url: 'https://www.naval-group.com/fr/carrieres' },
  { id: 183, nom: 'MBDA', secteur: 'Défense/Missiles', ats: 'custom', slug: null, careers_url: 'https://www.mbda-systems.com/fr/carrieres' },
  { id: 184, nom: 'Nexter', secteur: 'Défense terrestre', ats: 'custom', slug: null, careers_url: 'https://www.nexter-group.fr/fr/carrieres' },
  { id: 185, nom: 'Faurecia/Forvia', secteur: 'Automobile', ats: 'workday', slug: 'forvia', careers_url: 'https://careers.forvia.com' },
  { id: 186, nom: 'Valeo', secteur: 'Automobile', ats: 'workday', slug: 'valeo', workday_id: 'valeo', workday_path: 'valeo_jobs', careers_url: 'https://www.valeo.com/fr/carrieres' },
  { id: 187, nom: 'Roquette', secteur: 'Agroalimentaire/Chimie', ats: 'workday', workday_id: 'roquette', workday_path: 'External', workday_subdomain: 'wd3', careers_url: 'https://www.roquette.com/fr/carrieres' },
  { id: 188, nom: 'Lactalis', secteur: 'Agroalimentaire', ats: 'custom', slug: null, careers_url: 'https://carrieres.lactalis.fr' },
  { id: 189, nom: 'Bonduelle', secteur: 'Agroalimentaire', ats: 'workday', slug: 'bonduelle', careers_url: 'https://www.bonduelle.com/fr/carrieres' },
  { id: 190, nom: 'Tereos', secteur: 'Agroalimentaire/Sucre', ats: 'recruitee', slug: 'tereos', careers_url: 'https://www.tereos.com/fr/nous-rejoindre' },
  { id: 191, nom: 'InVivo', secteur: 'Agroalimentaire', ats: 'custom', slug: null, careers_url: 'https://www.invivo-group.com/fr/carrieres' },
  { id: 192, nom: 'Bigard', secteur: 'Agroalimentaire', ats: 'custom', slug: null, careers_url: 'https://www.bigard.fr/carrieres' },

  // ═══ TRANSPORT ET LOGISTIQUE ══════════════════════════════════════════
  { id: 193, nom: 'Air France-KLM', secteur: 'Aviation', ats: 'greenhouse', slug: 'air', careers_url: 'https://careers.airfranceklm.com' },
  { id: 194, nom: 'XPO Logistics France', secteur: 'Logistique', ats: 'workday', slug: 'xpo', careers_url: 'https://www.xpo.com/fr-fr/carrieres' },
  { id: 195, nom: 'Geodis', secteur: 'Logistique', ats: 'recruitee', slug: 'geodis', careers_url: 'https://geodis.com/fr/carrieres' },
  { id: 196, nom: 'FM Logistic', secteur: 'Logistique', ats: 'recruitee', slug: 'fm', careers_url: 'https://www.fmlogistic.com/fr/carrieres' },
  { id: 197, nom: 'Transdev', secteur: 'Transport', ats: 'custom', slug: null, careers_url: 'https://www.transdev.com/fr/carrieres' },
  { id: 198, nom: 'Keolis', secteur: 'Transport', ats: 'recruitee', slug: 'keolis', careers_url: 'https://www.keolis.com/fr/carrieres' },
  { id: 199, nom: 'Bolloré Logistics', secteur: 'Logistique', ats: 'smartrecruiters', slug: 'bolloregroup', careers_url: 'https://www.bollore-logistics.com/fr/carrieres' },
  { id: 200, nom: 'CMA CGM', secteur: 'Transport maritime', ats: 'greenhouse', slug: 'cma', careers_url: 'https://www.cmacgm-group.com/fr/carrieres' },

  // ═══ CABINETS DE CONSEIL ET AUDIT ═════════════════════════════════════
  { id: 201, nom: 'Michael Page', secteur: 'Recrutement', ats: 'greenhouse', slug: 'michaelpage', careers_url: 'https://www.michaelpage.fr/jobs' },
  { id: 202, nom: 'Robert Half', secteur: 'Recrutement', ats: 'recruitee', slug: 'robert', careers_url: 'https://www.roberthalf.fr/emplois' },
  { id: 203, nom: 'Hays France', secteur: 'Recrutement', ats: 'greenhouse', slug: 'hays', careers_url: 'https://www.hays.fr/emploi' },
  { id: 204, nom: 'Adecco France', secteur: 'Recrutement', ats: 'recruitee', slug: 'adecco', careers_url: 'https://www.adecco.fr/candidat' },
  { id: 205, nom: 'Manpower France', secteur: 'Recrutement', ats: 'smartrecruiters', slug: 'manpowerfrance', careers_url: 'https://www.manpower.fr/candidats' },
  { id: 206, nom: 'Randstad France', secteur: 'Recrutement', ats: 'personio', slug: 'randstad', careers_url: 'https://www.randstad.fr/candidat' },
  { id: 207, nom: 'PageGroup', secteur: 'Recrutement', ats: 'workday', slug: 'pagegroup', workday_id: 'pagegroup', careers_url: 'https://www.pagegroup.fr' },
  { id: 208, nom: 'Expectra', secteur: 'Recrutement', ats: 'workday', slug: 'expectra', workday_id: 'randstad', careers_url: 'https://www.expectra.fr' },
  { id: 209, nom: 'McKinsey France', secteur: 'Conseil', ats: 'workday', slug: 'mckinsey', workday_id: 'mckinsey', careers_url: 'https://www.mckinsey.com/fr/carrieres' },
  { id: 211, nom: 'Roland Berger', secteur: 'Conseil', ats: 'smartrecruiters', slug: 'rolandberger', careers_url: 'https://www.rolandberger.com/fr/Carrieres' },
  { id: 212, nom: 'Oliver Wyman', secteur: 'Conseil', ats: 'lever', slug: 'oliverwyman', careers_url: 'https://www.oliverwyman.com/careers' },
  { id: 213, nom: 'Mazars', secteur: 'Audit/Conseil', ats: 'smartrecruiters', slug: 'mazars', careers_url: 'https://www.mazars.fr/Accueil/Carrieres' },
  { id: 214, nom: 'BDO France', secteur: 'Audit', ats: 'greenhouse', slug: 'bdofrance', careers_url: 'https://www.bdo.fr/carrieres' },
  { id: 215, nom: 'Inetum', secteur: 'IT/Conseil', ats: 'greenhouse', slug: 'inetum', careers_url: 'https://www.inetum.com/fr/carrieres' },
  { id: 216, nom: 'Aubay', secteur: 'IT/Conseil', ats: 'recruitee', slug: 'aubay', careers_url: 'https://www.aubay.com/fr/carriere' },
  { id: 217, nom: 'Devoteam', secteur: 'IT/Conseil', ats: 'smartrecruiters', slug: 'devoteam', careers_url: 'https://fr.devoteam.com/rejoindre-devoteam' },
  { id: 218, nom: 'Onepoint', secteur: 'IT/Conseil', ats: 'lever', slug: 'onepoint', careers_url: 'https://www.groupeonepoint.com/fr/carrieres' },
  { id: 219, nom: 'Ekimetrics', secteur: 'Data/Conseil', ats: 'lever', slug: 'ekimetrics', careers_url: 'https://ekimetrics.com/fr/rejoindre' },
  { id: 220, nom: 'Converteo', secteur: 'Data/Conseil', ats: 'lever', slug: 'converteo', careers_url: 'https://converteo.com/carrieres' },

  { id: 221, nom: 'AG2R La Mondiale', secteur: 'Assurance', ats: 'workday', workday_id: 'ag2rlamondiale', workday_path: 'Candidats', workday_subdomain: 'wd3', careers_url: 'https://ag2rlamondiale.wd3.myworkdayjobs.com' },
  { id: 222, nom: 'Banque de France', secteur: 'Finance publique', ats: 'workday', workday_id: 'bdf', workday_path: 'recrutement-banque-de-france', workday_subdomain: 'wd103', careers_url: 'https://bdf.wd103.myworkdayjobs.com' },
  { id: 223, nom: 'Deloitte France', secteur: 'Audit/Conseil', ats: 'workday', workday_id: 'fina', workday_path: 'DESrecrutement', workday_subdomain: 'wd103', careers_url: 'https://fina.wd103.myworkdayjobs.com' },
  { id: 224, nom: 'SNCF Connect Tech', secteur: 'Transport/Tech', ats: 'workday', workday_id: 'evoyageurs', workday_path: 'jobs', careers_url: 'https://evoyageurs.wd3.myworkdayjobs.com' },
  { id: 225, nom: 'Too Good To Go', secteur: 'FoodTech', ats: 'greenhouse', slug: 'toogoodtogo', careers_url: 'https://boards.greenhouse.io/toogoodtogo' },
  { id: 226, nom: 'Cultura', secteur: 'Commerce/Culture', ats: 'personio', slug: 'cultura', careers_url: 'https://cultura.wd3.myworkdayjobs.com' },
  { id: 227, nom: 'La Mutuelle Générale', secteur: 'Assurance', ats: 'workday', workday_id: 'lmg', workday_path: 'LMG', careers_url: 'https://lmg.wd3.myworkdayjobs.com' },
  { id: 228, nom: 'Abeille Assurances', secteur: 'Assurance', ats: 'workday', workday_id: 'abeilleassurances', workday_path: 'External', workday_subdomain: 'wd103', careers_url: 'https://abeilleassurances.wd3.myworkdayjobs.com' },
]

export const ATS_TYPES = ['greenhouse', 'lever', 'smartrecruiters', 'workday', 'successfactors', 'custom', 'taleo']
export const SECTEURS_FR = [...new Set(ENTREPRISES.map(e => e.secteur))]
